pipeline {
    agent none

    stages {

        stage('Back-end: Java Build') {
            agent {
                docker { image 'maven:3.8.1-adoptopenjdk-11' }
            }
            steps {
                dir('review') {
                    // Compile Java code
                    sh 'javac HelloWorld.java'

                    // Run Java code
                    sh 'java HelloWorld'
                }
            }
        }

        stage('Front-end: Node.js') {
            agent {
                docker { image 'node:16-alpine' }
            }
            steps {
                dir('review/frontend') {
                    // Run Node app
                    sh 'node app.js'
                }
            }
        }
    }
}
