pipeline {
  agent none
  stages {
    stage('Back-end') {
      agent {
        docker { image 'maven:3.8.1-adoptopenjdk-11' }
      }
      steps {
        sh 'docker run -d --name my-maven maven:3.8.1-adoptopenjdk-11 tail -f /dev/null'
      }
    }
    stage('Front-end') {
      agent {
        docker { image 'node:16-alpine' }
      }
      steps {
        sh 'docker run -d --name my-node node:16-alpine tail -f /dev/null'
      }
    }
  }
}
